name: Deploy Static Site to Netlify

on:
  push:
    branches:
      - master # Trigger workflow on push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Install Netlify CLI (Use npm to install the CLI globally)
    - name: Install Netlify CLI
      run: npm install -g netlify-cli

    # Step 3: Deploy to Netlify
    - name: Deploy to Netlify
      run: netlify deploy --prod --dir=./ # Use the correct directory path if needed
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
