name: Deploy Static Site to Netlify

on:
  push:
    branches:
      - master # Trigger workflow on push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Install Netlify CLI
    - name: Install Netlify CLI
      run: npm install -g netlify-cli

    # Step 3: Authenticate Netlify CLI (required for linking and deploying)
    - name: Authenticate with Netlify
      run: netlify login --token ${{ secrets.NETLIFY_AUTH_TOKEN }}
      
    # Step 4: Link the repository to Netlify (no need to specify --site)
    - name: Link to Netlify site
      run: netlify link --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}

    # Step 5: Deploy to Netlify
    - name: Deploy to Netlify
      run: netlify deploy --prod --dir=./  # Deploy your site
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
