name: Deploy Static Site to Netlify

on:
  push:
    branches:
      - master  # Trigger workflow on push to the master branch

jobs:
  deploy:
    runs-on: ${{matrix.os}}
    strategy:
      matrix: 
        os: [ubuntu-latest, window-latest, macOS-latest]
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Netlify CLI (Only if not installed globally already)
      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      # Step 3: Deploy to the Recipe-Finder site using the site ID
      - name: Deploy to Recipe-Finder Site
        run: |
          netlify deploy --prod --dir=./ --site ${{ secrets.NETLIFY_SITE_ID }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
