name: Deploy Static Site to Netlify

on:
  push:
    branches:
      - master # Trigger workflow on push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Install dependencies (Only if needed for additional packages like npm for JS)
    - name: Install dependencies
      run: |
        npm install

    # Step 3: Deploy to Netlify
    - name: Deploy to Netlify
      run: |
        curl -sL https://github.com/netlify/cli/releases/download/v3.0.0-beta.10/netlify-cli-linux-x64.tar.gz | tar xz
        ./netlify-cli deploy --prod --dir=./  
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
